#!/bin/bash
LC_ALL=en_US.UTF-8
export LC_ALL
PYTHONUNBUFFERED=true
export PYTHONUNBUFFERED
source ~/.remote
asciinema rec /var/recordings/$USER.json -c "ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no root@${REMOTE}" -w 2